[build]
  command = "npx prisma generate && CI=false npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NETLIFY_DISABLE_CACHE = "true"
  # Completely disable Go
  NETLIFY_GO_SKIP = "true"
  GO_SKIP_INSTALL = "true"

# Explicitly skip Go installation
[build.lifecycle]
  onInit = "echo 'Completely skipping Go installation - not required for this project'"
  onBuild = "echo 'No Go build steps needed'"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add build caching
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Cache Control headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 